name: Deprecate NPM Package Version

on:
  workflow_dispatch:
    inputs:
      npm_version:
        description: 'NPM package version'
        required: true
      next_version_template:
        description: 'Template for minimum working next version'
        required: true

env:
  package_name: vue-scroll-table

jobs:
  deprecate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install NPM CLI
        run: npm install -g npm@latest

      - name: Log in to NPM registry
        run: echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Deprecate NPM package version
        run: |
          next_version_template="${{ github.event.inputs.next_version_template }}"
          next_version="$(printf "$next_version_template" ${{ github.event.inputs.npm_version }})"
          npm deprecate ${{ env.package_name }}@${{ github.event.inputs.npm_version }} "This version is deprecated, please upgrade to $next_version."
