name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10.15
      - run: npm ci
      - run: npm run build
      - run: cp -R dist/ package-dist/  # Copy the contents of the dist folder to a new directory named package-dist

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10.15
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: echo "package-dist" > .npmignore  # Create a .npmignore file with "package-dist" as the content
      - run: npm pack
      - run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
