name: Unpublish NPM Package Version

on:
  workflow_dispatch:
    inputs:
      npm_version:
        description: 'NPM package version'
        required: true

jobs:
  unpublish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Unpublish NPM package
        run: |
          # Install NPM CLI
          npm install -g npm@latest

          # Log in to NPM registry
          echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > ~/.npmrc

          # Unpublish the specified version
          npm unpublish your-package@${{ github.event.inputs.npm_version }} --force
