name: Unpublish NPM Package Version

on:
  workflow_dispatch:
    inputs:
      npm_version:
        description: 'NPM package version'
        required: true

env:
  package_name: vue-scroll-table

jobs:
  unpublish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install NPM CLI
        run: npm install -g npm@latest

      - name: Log in to NPM registry
        run: echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Unpublish NPM package version
        run: |
          npm show ${{ env.package_name }}@${{ github.event.inputs.npm_version }} > package-info.txt
          npm publish --dry-run
          npm unpublish ${{ env.package_name }}@${{ github.event.inputs.npm_version }} --force
